- name: Demo on tasks tag
  hosts: all
  tasks: 
    - name: CentOS
      debug:
        msg: CentOS
      tags:
        

    - name: Ubuntu
      debug:
        msg: Ubuntu
      tags:
        - Ubuntu
