- name: Loops
  hosts: localhost
  tasks:
    - name: print
      debug:
        msg: Hello, {{item}}
      loop:
        - John
        - Ram
    - name: Print Loop from Map
      debug:
        msg: Hello {{item.name}}, Welcome to {{item.course}} traning
      loop:
        - {{ name: Jhon, course: AWS }}
        - {{ name: Ram,  course: DevOps }