  filebeat.inputs:
  - type: log
    enabled: true
    fields:
      appName: {{COMPONENT}}
    paths:
     {% if NGINX is defined %}
  - /var/log/nginx/access.log
      {% else %}
      - /var/log/{{COMPONENT}}.log
    {% endif %}

{% if JAVA is defined %}
    multiline.pattern: "^[0-9][0-9][0-9][0-9]-"
    multiline.negate: true
    multiline.match: after
{% endif %}

{% if OUTPUT_TO == "elasticsearch" %}
    json.keys_under_root: true
setup.template.name: "{{COMPONENT}}"
setup.template.pattern: "{{COMPONENT}}-*"
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch.roboshop.internal:9200"]
  index: "{{COMPONENT}}-%{+yyyy.MM.dd}"
{% endif %}

{% if OUTPUT_TO == "logstash" %}
output.logstash:
  hosts: ["elasticsearch.roboshop.internal:5044"]
{% endif %}

### Default Configuration
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
~