filebeat.inputs:
  - type: log
    enabled: true
    json.keys_under_root: true
    paths:
      - /var/log/{{COMPONENT}}.log

{% if OUTPUT_TO == "elasticsearch" %}
setup.template.name: "{{COMPONENT}}"
setup.template.pattern: "{{COMPONENT}}-*"
setup.ilm.enabled: false


output.elasticsearch:
  hosts: ["elasticsearch.roboshop.internal:9200"]
  index: "{{COMPONENT}}-%{+yyyy.MM.dd}"
{% endif %}

### Default Configuration
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~  