- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Download Frontend Archive
  ansible.builtin.unarchive:
    src: "httphttps://github.com/roboshop-devops-project/frontend/archive/main.zip"