- name: Install Erlang 
  yum: 
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm

- name: Setup YUM repos
  copy: 
    src
   
- name: Install RabbitMQ Server
  yum: 
    name: rabbitmq-server
    state: present

- name: Start RabbitMQ Server
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Create RoboShop app user
  community.rabbitmq.rabbitmq_user:
    user: robosshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administator