- name: Copy MySQL Repo
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove mariadb-libs Package
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL Serverr
  yum:
    name:
      - mysql-community-server
      - MySQL-python
    state: present

- name: Start MySQL Service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the Password Reset status
  shell: echo 'show databases' | mysql -uroot -pRoboShop@1
  register: out
  ignore_errors: yes

- name: Grab default Password
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: default_pass
  when: out.rc != 0

- name: Reset SQL file
  copy:
    src: reset.sql
    dest: /tmp/reset.sql
  when: out.rc != 0

- name: Reset MySQL Password
  shell: mysql --connect-expired-password -u root -p"{{default_pass.stdout}}" </tmp/reset.sql
  when: out.rc != 0
   