- name: Install NodeJS
  yum:
    name: 
      - NodeJS
      - make 
      - gcc-c++
    state: present

- name: Create Roboshop App User
  user:
   name: roboshop

- name: Catalogue App Archive
  ansibli.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Remove old content
  ansible.builtin.file:
    path: