- name: Update Prometheus Config
  template: 
    src: {{item}}.yml
    dest: /opt/prometheus/prometheus.yml
  loop:
    - prometheus
    - alerts
    - records
  
- name: Restart Prometheus Service
  systemd:
    name: prometheus
    state: restarted
    enabled: yes