- name: Donwload Node Exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{NE_VERSION}}/node_exporter-{{NE_VERSION}}.linux-amd64.tar.gz"
    dest: /opt
    remote_src: yes

- name: Create link of Prometheus with standard directory name
  ansible.builtin.file

- name: Copy SystemD file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start Node exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes