- name: Install NodeJS
  yum:
    name: 
      - nodejs
      - make 
      - gcc-c++
    state: present

- name: Doenload
  include_tasks: download.yml

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

