- name: Install python
  yum:
    name: 
      - python36
      - gcc 
      - python3-devel
    state: present

- name: Doenload
  include_tasks: download.yml

- name: Install python Dependencies
  pip: 
    requirements: /home/roboshop/requirements.txt

- name: SystemD
  include_tasks: systemd.yml