groups:
- name: HardwareResources
  rules:
  - alert: HighCPU
    expr: CPU_usage_in_percentage > 80
    for: 11s
    labels:
      severity: critical
    annotations:
      summary: HighCPU on {%raw%}{{ $labels.instance }}{%endraw%}
    