groups:
- name: HardwareResources
  rules:
  - alert: HighCPU
    expr: CPU_usage_in_percentage > 90
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: HighCPU on  \{{ $labeles.tagName }}