groups:
- name: HardwareResources
  rules:
  - alert: HighCPU
    expr: CPU_usage_in_percentage = 100
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: HighCPU on {%raw%}{{ $labels.instance }}{%endraw%}
    