- name: Install NodeJS
  yum:
    name: 
      - nodejs
      - make 
      - gcc-c++
    state: present

- name: Create Roboshop App User
  user:
   name: roboshop

- name: Download {{COMPONENT}} App Archive
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/cart/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Remove old content
  ansible.builtin.file:
    path: /home/roboshop/cart
    state: absent

- name: Copy Extracted Content to cart Path
  ansible.builtin.copy:
    src: /tmp/cart-main/
    dest: /home/roboshop/cart
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/cart
  become_user: roboshop

- name: Setup cart Service File
  copy:
    src: systemd.service
    dest: /etc/systemd/system/cart.service

- name: Start cart Service
  systemd:
    name: cart
    state: restarted
    enabled: yes
    daemon_reload: yes